// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations usam a conexão direta (session pooler); o app usa o
    // transaction pooler via DATABASE_URL no driver pg.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
